### ISSUE TITLE
Open editor from another folder

### ISSUE THREAD

**Issue by Oulfin** [lithium0003/JSME_ipywidget#2]
Hi,

Thanks for this useful tool, 

I do not have java knowledge and I am wondering if it is possible to open the editor from another folder.

I thought it was enough by changing this; 

require(['jsme/jsme.nocache.js']) **by** require(['/home/random/Desktop/JSME_ipywidget-master/jsme/jsme.nocache.js'])

However it does not do anything only shows the text SMILES: , but not the editor.

Does one always have to be cd in JSME_ipywidget folder to activate the editor?

Thanks!

Best regards,

**Comment by lithium0003** [comment]
Hello,
Thanks using tool,

"require" command maybe intend to load inside of package, so its path starts package current dir.
Other solution, you can make symlink into the folder from other.

Thanks.

**Comment by Oulfin** [comment]
Thank you very much!

I could make it work with symlink.

Best,
